github_packages_token: ENC[AES256_GCM,data:tTH2bQgexfH16gYT0vA052FuYFUDCCEx65DXI0QRtcWOzjPCbh/fAw==,iv:b3kpcscyqfBFjxCEg8wkMPprbEQCoTAWkiyK8zSfDZ0=,tag:Tw87EBYaskg7fvF3as+S7g==,type:str]
github_vcc_token: ENC[AES256_GCM,data:xrJRPnusgLLKz6Rie/d0OTLNn/DvQvGVa0HOrd2ulGQYOkwA3wfRAQ==,iv:uStYk3b79CoyrQJD5qYInsi+7rthM6ipgV09W96lqP4=,tag:0VddUBI+R0bFLrI17heAgw==,type:str]
clockify_api_key: ENC[AES256_GCM,data:wr9q3ng58Ou1Yr9xZNKgDMLzCKJ/cZ+oC8JwNPZAFGSo1U+Yv3esgis+HrAQ6tQI,iv:FYyp2unPKwAcKsACjiSNmFkz8gOxJhr7gzt9p1UTGYg=,tag:EHgb1kmLmceIHnuUUORm+Q==,type:str]
sops:
    age:
        - recipient: age1z5qy8fnarchqsvzeuppq8xmalweknnmhfu2t5kkqfken6p72n4sqf4tqy2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTmhXbUVZNGFrZ1c1VGV6
            UzVDK2Nvck1EUFRuWUl3UFVsTG1tenl5M1RFCk9kMjdlVXRkUjlsd0lpU0xlS1Ew
            UTNZWmdYaThRUmVXdXBFOHI5b3JoK00KLS0tIGpTYU8vQW40cE14T2hQakpSOGl0
            SFg1QVZzVi9lYVM0MVoyL1hSMU1IcG8Kji4CFS5iwZ17/dOIkDPwH0D75J9xmvXW
            Y4Vs9gNlj22lU61Bu9r9Fxno36F69OpFAyH4Umc/gZr7FLUKK7efTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T15:54:52Z"
    mac: ENC[AES256_GCM,data:m89uX/kq3B43nzXMvijmaj+UmnclFAkS1sBkw4RMB5rB3bqgoyamNgyJWmq8yFNYNaaYQwnhWOtacGidjsSNydUKNB7k0pnwhhJgWiFi8lMSCGrzE39tpNP2taAk7OebHlwTPXcfJd0g+mhHYT6ump9ajW9fIzqX5dmeG2cqXSI=,iv:p51IkkTwXRbsqyY5Yq75fwzHmyKpoyTvKPJw0yeU1YY=,tag:0NH43VT5DPFgRuA8aufB2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
