vim.cmd("highlight clear")
vim.cmd("colorscheme oh-lucy")
vim.cmd("set background=dark")
vim.cmd("hi Cursor guibg=#6e7380")
vim.cmd("hi lualine_c_command guibg=#14161d")
vim.cmd("hi lualine_c_inactive guibg=#14161d")
vim.cmd("hi lualine_c_insert guibg=#14161d")
vim.cmd("hi lualine_c_normal guibg=#14161d")
vim.cmd("hi lualine_c_replace guibg=#14161d")
vim.cmd("hi lualine_c_terminal guibg=#14161d")
vim.cmd("hi lualine_c_visual guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_command_to_lualine_c_command guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_inactive_to_lualine_c_inactive guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_insert_to_lualine_c_insert guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_normal_to_lualine_c_normal guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_replace_to_lualine_c_replace guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_terminal_to_lualine_c_terminal guibg=#14161d")
vim.cmd("hi lualine_transitional_lualine_b_visual_to_lualine_c_visual guibg=#14161d")